# Generated by Django 4.2.3 on 2023-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание статьи')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография к статье')),
            ],
            options={
                'verbose_name': 'Блоги',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Paid_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('photo', models.ImageField(upload_to='p_servicesPhoto/%Y/%m/%d/', verbose_name='Фотография')),
                ('price_service', models.TextField(verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'Платные услуги',
                'verbose_name_plural': 'Платные услуги',
            },
        ),
        migrations.CreateModel(
            name='Progess_institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='files_reward/%Y/%m/%d/', verbose_name='Документы наград / лицензий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress_photo/%Y/%m/%d/', verbose_name='Фотография под документ(необязательно)')),
            ],
            options={
                'verbose_name': 'Достижения/лицензии',
                'verbose_name_plural': 'Достижения/лицензии',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО ученика')),
                ('passport', models.CharField(max_length=50, verbose_name='Паспорт ученика')),
                ('full_name_parent', models.CharField(max_length=50, verbose_name='ФИО родителя')),
                ('passport_parent', models.CharField(max_length=50, verbose_name='Паспорт родителя')),
                ('class_student', models.IntegerField(verbose_name='Номер класса ученика')),
                ('information_file', models.FileField(null=True, upload_to='files/%Y/%m/%d/', verbose_name='Файл с информацией об ученике')),
                ('question_instuction', models.CharField(blank=True, max_length=700, null=True, verbose_name='Вопрос учреждению')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО преподавателя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('posititon', models.CharField(max_length=100, verbose_name='Должность и предмет обучения')),
                ('description', models.TextField(verbose_name='Информация о карьере преподавателя')),
                ('photo', models.ImageField(null=True, upload_to='photos_teacher/%Y/%m/%d/', verbose_name='Фотография преподавателя')),
            ],
            options={
                'verbose_name': 'Преподаватели',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
